app = 'dataplate'
primary_region = 'gru'

[build]

[env]
  SPRING_PROFILES_ACTIVE = 'prod'
  SPRING_DATASOURCE_URL = 'jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.co:6543/postgres?prepareThreshold=0'
  SPRING_DATASOURCE_USERNAME = 'postgres.zcdjzwnzapzvislInivh'

[[services]]
  internal_port = 8080
  protocol = 'tcp'

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1