app = 'dataplate'
primary_region = 'gru'

[build]

[env]
  SPRING_PROFILES_ACTIVE = 'prod'
  SPRING_DATASOURCE_URL = 'jdbc:postgresql://db.zcdjzwnzapzvisllnivh.supabase.co:5432/postgres'
  SPRING_DATASOURCE_USERNAME = 'postgres.zcdjzwnzapzvisllnivh'

[[services]]
  internal_port = 8080
  protocol = 'tcp'

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.health]
    type = 'http'
    port = 8080
    method = 'GET'
    path = '/actuator/health'
    interval = '15s'
    timeout = '5s'
    grace_period = '60s'